'use server';

/**
 * @fileOverview A flow that generates project details based on a user-provided prompt.
 *
 * - generateProjectDetails - A function that triggers the project detail generation flow.
 * - GenerateProjectDetailsInput - The input type for the generateProjectDetails function.
 * - GenerateProjectDetailsOutput - The return type for the generateProjectDetails function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProjectDetailsInputSchema = z.object({
  prompt: z.string().describe('A brief description of the desired project.'),
});
export type GenerateProjectDetailsInput = z.infer<
  typeof GenerateProjectDetailsInputSchema
>;

const GenerateProjectDetailsOutputSchema = z.object({
  projectDetails: z
    .string()
    .describe('A detailed description of the project generated by the AI.'),
});
export type GenerateProjectDetailsOutput = z.infer<
  typeof GenerateProjectDetailsOutputSchema
>;

export async function generateProjectDetails(
  input: GenerateProjectDetailsInput
): Promise<GenerateProjectDetailsOutput> {
  return generateProjectDetailsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProjectDetailsPrompt',
  input: {schema: GenerateProjectDetailsInputSchema},
  output: {schema: GenerateProjectDetailsOutputSchema},
  prompt: `You are a helpful assistant that expands upon a user's initial project idea to create detailed project requirements.  The user's idea is: {{{prompt}}}.  Create a detailed description of the project. `,
});

const generateProjectDetailsFlow = ai.defineFlow(
  {
    name: 'generateProjectDetailsFlow',
    inputSchema: GenerateProjectDetailsInputSchema,
    outputSchema: GenerateProjectDetailsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
